[package]
name = "licensebat-dart"
version = "0.0.1"
edition = "2021"
authors = ["Roberto Huertas <roberto.huertas@outlook.com>"]
description = "A library to get information about your Dart dependencies"
license = "MIT"
repository = "https://github.com/licensebat/licensebat-dart"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# core
licensebat-core = { path = "../licensebat-core" }
# serialization
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
# utils
futures = { version = "0.3.6" } 
tracing = "0.1"
reqwest = "0.11"
# html scraper
scraper = "0.12"
selectors = "0.22" # don't update for the moment. 0.23 breaks
# spdx
askalono = "0.4.3"

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }

[build-dependencies]
askalono = { version = "0.4.3" }
