[package]
name = "licensebat-core"
version = "0.1.0"
authors = ["Roberto Huertas <roberto.huertas@outlook.com>"]
description = "Types and Traits for building Licensebat libraries"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
yarn-lock-parser = "0.1.1"
# utils
futures = { version = "0.3.6" } 
tracing = "0.1"
# errors
thiserror = "1.0.21"