[package]
name = "licensebat-cli"
version = "0.1.0"
authors = ["Roberto Huertas <roberto.huertas@outlook.com>"]
description = "CLI tool to manage dependencies' license validation"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "licensebat"
path = "src/main.rs"

[dependencies]
# core libs
licensebat-core = { path = "../licensebat-core" }
# cli
structopt = "0.3.25"